package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Adjunto generated by hbm2java
 */
public class Adjunto  implements java.io.Serializable {


     private Integer id;
     private Idea idea;
     private ItemCatalogo itemCatalogo;
     private String nombre;
     private Date register;

    public Adjunto() {
    }

	
    public Adjunto(Idea idea) {
        this.idea = idea;
    }
    public Adjunto(Idea idea, ItemCatalogo itemCatalogo, String nombre, Date register) {
       this.idea = idea;
       this.itemCatalogo = itemCatalogo;
       this.nombre = nombre;
       this.register = register;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Idea getIdea() {
        return this.idea;
    }
    
    public void setIdea(Idea idea) {
        this.idea = idea;
    }
    public ItemCatalogo getItemCatalogo() {
        return this.itemCatalogo;
    }
    
    public void setItemCatalogo(ItemCatalogo itemCatalogo) {
        this.itemCatalogo = itemCatalogo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getRegister() {
        return this.register;
    }
    
    public void setRegister(Date register) {
        this.register = register;
    }




}


