package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1



/**
 * Ciiu generated by hbm2java
 */
public class Ciiu  implements java.io.Serializable {


     private Integer id;
     private Integer padre;
     private String codigo;
     private String nombre;

    public Ciiu() {
    }

    public Ciiu(Integer padre, String codigo, String nombre) {
       this.padre = padre;
       this.codigo = codigo;
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getPadre() {
        return this.padre;
    }
    
    public void setPadre(Integer padre) {
        this.padre = padre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


