package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Convocatoria generated by hbm2java
 */
public class Convocatoria  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String imagen;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;

    public Convocatoria() {
    }

    public Convocatoria(String nombre, String imagen, String descripcion, Date fechaInicio, Date fechaFin) {
       this.nombre = nombre;
       this.imagen = imagen;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


