package model;
// Generated 20-jun-2017 17:34:46 by Hibernate Tools 4.3.1



/**
 * ConvocatoriaResponsable generated by hbm2java
 */
public class ConvocatoriaResponsable  implements java.io.Serializable {


     private Integer id;
     private Convocatoria convocatoria;
     private Usuario usuario;

    public ConvocatoriaResponsable() {
    }

    public ConvocatoriaResponsable(Convocatoria convocatoria, Usuario usuario) {
       this.convocatoria = convocatoria;
       this.usuario = usuario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Convocatoria getConvocatoria() {
        return this.convocatoria;
    }
    
    public void setConvocatoria(Convocatoria convocatoria) {
        this.convocatoria = convocatoria;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

}


