package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Evaluacion generated by hbm2java
 */
public class Evaluacion  implements java.io.Serializable {


     private Integer id;
     private Idea idea;
     private ItemCatalogo itemCatalogo;
     private Usuario usuario;
     private String comentario;
     private Date register;

    public Evaluacion() {
    }

	
    public Evaluacion(Idea idea, ItemCatalogo itemCatalogo, Usuario usuario) {
        this.idea = idea;
        this.itemCatalogo = itemCatalogo;
        this.usuario = usuario;
    }
    public Evaluacion(Idea idea, ItemCatalogo itemCatalogo, Usuario usuario, String comentario, Date register) {
       this.idea = idea;
       this.itemCatalogo = itemCatalogo;
       this.usuario = usuario;
       this.comentario = comentario;
       this.register = register;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Idea getIdea() {
        return this.idea;
    }
    
    public void setIdea(Idea idea) {
        this.idea = idea;
    }
    public ItemCatalogo getItemCatalogo() {
        return this.itemCatalogo;
    }
    
    public void setItemCatalogo(ItemCatalogo itemCatalogo) {
        this.itemCatalogo = itemCatalogo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Date getRegister() {
        return this.register;
    }
    
    public void setRegister(Date register) {
        this.register = register;
    }




}


