package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1



/**
 * Funcionalidad generated by hbm2java
 */
public class Funcionalidad  implements java.io.Serializable {


     private Integer id;
     private String padre;
     private String nombre;
     private String url;
     private Boolean estado;
     private String icono;

    public Funcionalidad() {
    }

    public Funcionalidad(String padre, String nombre, String url, Boolean estado, String icono) {
       this.padre = padre;
       this.nombre = nombre;
       this.url = url;
       this.estado = estado;
       this.icono = icono;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPadre() {
        return this.padre;
    }
    
    public void setPadre(String padre) {
        this.padre = padre;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public Boolean getEstado() {
        return this.estado;
    }
    
    public void setEstado(Boolean estado) {
        this.estado = estado;
    }
    public String getIcono() {
        return this.icono;
    }
    
    public void setIcono(String icono) {
        this.icono = icono;
    }




}


