package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Idea generated by hbm2java
 */
public class Idea  implements java.io.Serializable {


     private Integer id;
     private Convocatoria convocatoria;
     private Ciiu ciiu;
     private ItemCatalogo itemCatalogoByEstado;
     private ItemCatalogo itemCatalogoByTipo;
     private ItemCatalogo itemCatalogoByEstadoGestacion;
     private Usuario usuario;
     private String nombre;
     private String descripcion;
     private String objetivo;
     private String mercadoPotencial;
     private String kw;
     private String lugar;
     private String imagen;
     private Date register;
     private String facebook;
     private String twitter;
     private String youtube;
     private Boolean publicar;
     private String estadoComentario;
     private Integer tipoIdea;
     private String comentarioEvaluacion;

    public Idea() {
    }

	
    public Idea(Convocatoria convocatoria) {
        this.convocatoria = convocatoria;
    }
    public Idea(Convocatoria convocatoria, Ciiu ciiu, ItemCatalogo itemCatalogoByEstado, ItemCatalogo itemCatalogoByTipo, ItemCatalogo itemCatalogoByEstadoGestacion, Usuario usuario, String nombre, String descripcion, String objetivo, String mercadoPotencial, String kw, String lugar, String imagen, Date register, String facebook, String twitter, String youtube, Boolean publicar, String estadoComentario, Integer tipoIdea) {
       this.convocatoria = convocatoria;
       this.ciiu = ciiu;
       this.itemCatalogoByEstado = itemCatalogoByEstado;
       this.itemCatalogoByTipo = itemCatalogoByTipo;
       this.itemCatalogoByEstadoGestacion = itemCatalogoByEstadoGestacion;
       this.usuario = usuario;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.objetivo = objetivo;
       this.mercadoPotencial = mercadoPotencial;
       this.kw = kw;
       this.lugar = lugar;
       this.imagen = imagen;
       this.register = register;
       this.facebook = facebook;
       this.twitter = twitter;
       this.youtube = youtube;
       this.publicar = publicar;
       this.estadoComentario = estadoComentario;
       this.tipoIdea = tipoIdea;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Convocatoria getConvocatoria() {
        return this.convocatoria;
    }
    
    public void setConvocatoria(Convocatoria convocatoria) {
        this.convocatoria = convocatoria;
    }
    public Ciiu getCiiu() {
        return this.ciiu;
    }
    
    public void setCiiu(Ciiu ciiu) {
        this.ciiu = ciiu;
    }
    public ItemCatalogo getItemCatalogoByEstado() {
        return this.itemCatalogoByEstado;
    }
    
    public void setItemCatalogoByEstado(ItemCatalogo itemCatalogoByEstado) {
        this.itemCatalogoByEstado = itemCatalogoByEstado;
    }
    public ItemCatalogo getItemCatalogoByTipo() {
        return this.itemCatalogoByTipo;
    }
    
    public void setItemCatalogoByTipo(ItemCatalogo itemCatalogoByTipo) {
        this.itemCatalogoByTipo = itemCatalogoByTipo;
    }
    public ItemCatalogo getItemCatalogoByEstadoGestacion() {
        return this.itemCatalogoByEstadoGestacion;
    }
    
    public void setItemCatalogoByEstadoGestacion(ItemCatalogo itemCatalogoByEstadoGestacion) {
        this.itemCatalogoByEstadoGestacion = itemCatalogoByEstadoGestacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public String getMercadoPotencial() {
        return this.mercadoPotencial;
    }
    
    public void setMercadoPotencial(String mercadoPotencial) {
        this.mercadoPotencial = mercadoPotencial;
    }
    public String getKw() {
        return this.kw;
    }
    
    public void setKw(String kw) {
        this.kw = kw;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }
    public String getImagen() {
        return this.imagen;
    }
    
    public void setImagen(String imagen) {
        this.imagen = imagen;
    }
    public Date getRegister() {
        return this.register;
    }
    
    public void setRegister(Date register) {
        this.register = register;
    }
    public String getFacebook() {
        return this.facebook;
    }
    
    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    public String getTwitter() {
        return this.twitter;
    }
    
    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    public String getYoutube() {
        return this.youtube;
    }
    
    public void setYoutube(String youtube) {
        this.youtube = youtube;
    }
    public Boolean getPublicar() {
        return this.publicar;
    }
    
    public void setPublicar(Boolean publicar) {
        this.publicar = publicar;
    }
    public String getEstadoComentario() {
        return this.estadoComentario;
    }
    
    public void setEstadoComentario(String estadoComentario) {
        this.estadoComentario = estadoComentario;
    }
    public Integer getTipoIdea() {
        return this.tipoIdea;
    }
    
    public void setTipoIdea(Integer tipoIdea) {
        this.tipoIdea = tipoIdea;
    }

    /**
     * @return the comentarioEvaluacion
     */
    public String getComentarioEvaluacion() {
        return comentarioEvaluacion;
    }

    /**
     * @param comentarioEvaluacion the comentarioEvaluacion to set
     */
    public void setComentarioEvaluacion(String comentarioEvaluacion) {
        this.comentarioEvaluacion = comentarioEvaluacion;
    }




}


