package model;
// Generated 20-jun-2017 17:28:51 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UsuarioAuth generated by hbm2java
 */
public class UsuarioAuth  implements java.io.Serializable {


     private Integer id;
     private Usuario usuario;
     private String user;
     private String password;
     private Date ultimoIngreso;

    public UsuarioAuth() {
    }

	
    public UsuarioAuth(Usuario usuario, String user) {
        this.usuario = usuario;
        this.user = user;
    }
    public UsuarioAuth(Usuario usuario, String user, String password, Date ultimoIngreso) {
       this.usuario = usuario;
       this.user = user;
       this.password = password;
       this.ultimoIngreso = ultimoIngreso;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getUser() {
        return this.user;
    }
    
    public void setUser(String user) {
        this.user = user;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getUltimoIngreso() {
        return this.ultimoIngreso;
    }
    
    public void setUltimoIngreso(Date ultimoIngreso) {
        this.ultimoIngreso = ultimoIngreso;
    }




}


